# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 683)
        MainWindow.setStyleSheet("background-color: rgb(0, 74, 112);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"\n"
"    border:none;\n"
"}\n"
"\n"
"QLabel{\n"
"color:rgb(235, 235, 235);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_13.setContentsMargins(0, -1, 7, -1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.left_menu = QtWidgets.QFrame(self.centralwidget)
        self.left_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu.setObjectName("left_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_menu)
        self.verticalLayout_2.setContentsMargins(-1, 19, 0, 22)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.left_menu)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_home = QtWidgets.QPushButton(self.frame)
        self.btn_home.setMinimumSize(QtCore.QSize(20, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_home.setFont(font)
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_home.setStyleSheet("QPushButton{\n"
"    \n"
"\n"
"    border-radius:2px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:5px;\n"
"    color: rgb(191, 236, 248);\n"
"}")
        self.btn_home.setObjectName("btn_home")
        self.horizontalLayout_4.addWidget(self.btn_home, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.left_menu)
        self.frame_2.setMinimumSize(QtCore.QSize(170, 0))
        self.frame_2.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(182, 182, 182);\n"
"\n"
"}\n"
"\n"
"QToolBox{\n"
"\n"
"text-align: left;\n"
"    background-color: rgb(228, 254, 255);\n"
"}\n"
"\n"
"QToolBox::tab{\n"
"    border-radius: 5px;\n"
"\n"
"    background-color: rgb(194, 232, 255);\n"
"    text-align: left;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox = QtWidgets.QToolBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.toolBox.setFont(font)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBox.setStyleSheet("QPushButton{\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:100px;\n"
"    background-color: rgb(200, 223, 223);\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.page_cadastro = QtWidgets.QWidget()
        self.page_cadastro.setGeometry(QtCore.QRect(0, 0, 170, 505))
        self.page_cadastro.setObjectName("page_cadastro")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_cadastro)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_cliente = QtWidgets.QPushButton(self.page_cadastro)
        self.btn_cliente.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_cliente.setFont(font)
        self.btn_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cliente.setStyleSheet("")
        self.btn_cliente.setObjectName("btn_cliente")
        self.verticalLayout_4.addWidget(self.btn_cliente)
        self.btn_produtos = QtWidgets.QPushButton(self.page_cadastro)
        self.btn_produtos.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_produtos.setFont(font)
        self.btn_produtos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_produtos.setStyleSheet("")
        self.btn_produtos.setObjectName("btn_produtos")
        self.verticalLayout_4.addWidget(self.btn_produtos)
        self.btn_pedidos = QtWidgets.QPushButton(self.page_cadastro)
        self.btn_pedidos.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_pedidos.setFont(font)
        self.btn_pedidos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pedidos.setStyleSheet("")
        self.btn_pedidos.setObjectName("btn_pedidos")
        self.verticalLayout_4.addWidget(self.btn_pedidos)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.toolBox.addItem(self.page_cadastro, "")
        self.page_historico = QtWidgets.QWidget()
        self.page_historico.setGeometry(QtCore.QRect(0, 0, 170, 505))
        self.page_historico.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.page_historico.setObjectName("page_historico")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_historico)
        self.verticalLayout_5.setContentsMargins(0, 5, 10, 0)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comboBox_clientes_historico = QtWidgets.QComboBox(self.page_historico)
        self.comboBox_clientes_historico.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_clientes_historico.setAccessibleName("")
        self.comboBox_clientes_historico.setAccessibleDescription("")
        self.comboBox_clientes_historico.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_clientes_historico.setStyleSheet("background-color: rgb(227, 230, 230);\n"
"\n"
"color: rgb(0,0,0);")
        self.comboBox_clientes_historico.setObjectName("comboBox_clientes_historico")
        self.comboBox_clientes_historico.addItem("")
        self.comboBox_clientes_historico.setItemText(0, "Cliente")
        self.verticalLayout_5.addWidget(self.comboBox_clientes_historico)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem1)
        self.calendar_inicio = QtWidgets.QCalendarWidget(self.page_historico)
        self.calendar_inicio.setMaximumSize(QtCore.QSize(160, 150))
        self.calendar_inicio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.calendar_inicio.setStyleSheet("background-color: rgb(227, 230, 230);\n"
"color: rgb(0, 0, 0);")
        self.calendar_inicio.setObjectName("calendar_inicio")
        self.verticalLayout_5.addWidget(self.calendar_inicio)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem2)
        self.calendar_fim = QtWidgets.QCalendarWidget(self.page_historico)
        self.calendar_fim.setMaximumSize(QtCore.QSize(160, 150))
        self.calendar_fim.setStyleSheet("background-color: rgb(227, 230, 230);\n"
"color: rgb(0, 0, 0);")
        self.calendar_fim.setObjectName("calendar_fim")
        self.verticalLayout_5.addWidget(self.calendar_fim)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem3)
        self.btn_gerar_relatorio = QtWidgets.QPushButton(self.page_historico)
        self.btn_gerar_relatorio.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_gerar_relatorio.setFont(font)
        self.btn_gerar_relatorio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gerar_relatorio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_gerar_relatorio.setStyleSheet("QPushButton:hover{\n"
"    border-radius:5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.btn_gerar_relatorio.setObjectName("btn_gerar_relatorio")
        self.verticalLayout_5.addWidget(self.btn_gerar_relatorio)
        self.toolBox.addItem(self.page_historico, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.gridLayout_13.addWidget(self.left_menu, 0, 0, 1, 1)
        self.main_container = QtWidgets.QFrame(self.centralwidget)
        self.main_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_container.setObjectName("main_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.main_container)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_3)
        self.btn_toggle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"C:\Users\thayl\OneDrive\Área de Trabalho\Projeto 4 Semestre\img\menu2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_toggle.setIcon(icon)
        self.btn_toggle.setIconSize(QtCore.QSize(32, 32))
        self.btn_toggle.setObjectName("btn_toggle")
        self.horizontalLayout_2.addWidget(self.btn_toggle)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.top_frame = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Century751 SeBd BT")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.top_frame.setFont(font)
        self.top_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout_2.addWidget(self.top_frame)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.frame_3)
        self.main_frame = QtWidgets.QFrame(self.main_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setStyleSheet("background-color: rgb(200, 223, 223);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Pages = QtWidgets.QStackedWidget(self.main_frame)
        self.Pages.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Pages.setObjectName("Pages")
        self.pg_home = QtWidgets.QWidget()
        self.pg_home.setObjectName("pg_home")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pg_home)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.logo = QtWidgets.QLabel(self.pg_home)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout_7.addWidget(self.logo)
        self.Pages.addWidget(self.pg_home)
        self.pg_cadastro_cliente = QtWidgets.QWidget()
        self.pg_cadastro_cliente.setObjectName("pg_cadastro_cliente")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pg_cadastro_cliente)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tab_cliente = QtWidgets.QTabWidget(self.pg_cadastro_cliente)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_cliente.sizePolicy().hasHeightForWidth())
        self.tab_cliente.setSizePolicy(sizePolicy)
        self.tab_cliente.setObjectName("tab_cliente")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem7, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.tab_1)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setStyleSheet("QPushButton:hover{\n"
"    border-radius:15px;\n"
"}\n"
"QLineEdit{\n"
"\n"
"    \n"
"    background-color: rgb(255,255,255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QFrame{\n"
"\n"
"    \n"
"        background-color: rgb(227, 230, 230);\n"
"\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem9, 4, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 11, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(50, 220, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 13, 2, 1, 1)
        self.lineEdit_nome_cliente = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nome_cliente.sizePolicy().hasHeightForWidth())
        self.lineEdit_nome_cliente.setSizePolicy(sizePolicy)
        self.lineEdit_nome_cliente.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEdit_nome_cliente.setMaximumSize(QtCore.QSize(2000, 25))
        self.lineEdit_nome_cliente.setMouseTracking(True)
        self.lineEdit_nome_cliente.setText("")
        self.lineEdit_nome_cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_nome_cliente.setObjectName("lineEdit_nome_cliente")
        self.gridLayout.addWidget(self.lineEdit_nome_cliente, 10, 1, 1, 2)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 12, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 12, 0, 1, 2)
        self.btn_salvar_cliente = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_salvar_cliente.sizePolicy().hasHeightForWidth())
        self.btn_salvar_cliente.setSizePolicy(sizePolicy)
        self.btn_salvar_cliente.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_salvar_cliente.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_salvar_cliente.setFont(font)
        self.btn_salvar_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salvar_cliente.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(205, 241, 252);\n"
"        border-radius:2px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius:15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.btn_salvar_cliente.setObjectName("btn_salvar_cliente")
        self.gridLayout.addWidget(self.btn_salvar_cliente, 12, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem14, 9, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 10, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 11, 3, 1, 1)
        self.lineEdit_contato_cliente = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_contato_cliente.sizePolicy().hasHeightForWidth())
        self.lineEdit_contato_cliente.setSizePolicy(sizePolicy)
        self.lineEdit_contato_cliente.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEdit_contato_cliente.setMaximumSize(QtCore.QSize(2000, 25))
        self.lineEdit_contato_cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_contato_cliente.setObjectName("lineEdit_contato_cliente")
        self.gridLayout.addWidget(self.lineEdit_contato_cliente, 11, 1, 1, 2)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem17, 10, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 4)
        self.gridLayout_2.addWidget(self.frame_5, 0, 1, 2, 1)
        self.tab_cliente.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem18 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem18, 0, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.tab_2)
        self.frame_8.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_8.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem19 = QtWidgets.QSpacerItem(20, 388, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem19, 1, 1, 1, 1)
        self.tableWidget_cliente = QtWidgets.QTableWidget(self.frame_8)
        self.tableWidget_cliente.setStyleSheet("\n"
"QLineEdit{\n"
"\n"
"    \n"
"    background-color: rgb(255,255,255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QFrame{\n"
"\n"
"    \n"
"        background-color: rgb(227, 230, 230);\n"
"\n"
"}\n"
"")
        self.tableWidget_cliente.setObjectName("tableWidget_cliente")
        self.tableWidget_cliente.setColumnCount(2)
        self.tableWidget_cliente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_cliente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_cliente.setHorizontalHeaderItem(1, item)
        self.gridLayout_8.addWidget(self.tableWidget_cliente, 0, 0, 2, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setStyleSheet("QPushButton{\n"
"    \n"
"        background-color: rgb(227, 230, 230);\n"
"    border-radius:2px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btn_alterar_cliente = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_alterar_cliente.sizePolicy().hasHeightForWidth())
        self.btn_alterar_cliente.setSizePolicy(sizePolicy)
        self.btn_alterar_cliente.setMinimumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_alterar_cliente.setFont(font)
        self.btn_alterar_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_alterar_cliente.setObjectName("btn_alterar_cliente")
        self.verticalLayout_13.addWidget(self.btn_alterar_cliente)
        self.btn_deletar_cliente = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_deletar_cliente.sizePolicy().hasHeightForWidth())
        self.btn_deletar_cliente.setSizePolicy(sizePolicy)
        self.btn_deletar_cliente.setMinimumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_deletar_cliente.setFont(font)
        self.btn_deletar_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_deletar_cliente.setObjectName("btn_deletar_cliente")
        self.verticalLayout_13.addWidget(self.btn_deletar_cliente)
        self.gridLayout_8.addWidget(self.frame_9, 0, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem20, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_8, 0, 1, 2, 1)
        spacerItem21 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem21, 0, 2, 1, 1)
        self.tab_cliente.addTab(self.tab_2, "")
        self.verticalLayout_8.addWidget(self.tab_cliente)
        self.Pages.addWidget(self.pg_cadastro_cliente)
        self.pg_cadastro_produto = QtWidgets.QWidget()
        self.pg_cadastro_produto.setObjectName("pg_cadastro_produto")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.pg_cadastro_produto)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tab_pedido = QtWidgets.QTabWidget(self.pg_cadastro_produto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_pedido.sizePolicy().hasHeightForWidth())
        self.tab_pedido.setSizePolicy(sizePolicy)
        self.tab_pedido.setObjectName("tab_pedido")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem22 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem22, 0, 2, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem23, 1, 1, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem24, 0, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.tab)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_7.setStyleSheet("QLineEdit{\n"
"\n"
"    \n"
"    background-color: rgb(255,255,255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QFrame{\n"
"\n"
"    \n"
"    background-color: rgb(227, 230, 230);\n"
"\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem25 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem25, 0, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem26, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 1, 1, 2)
        spacerItem27 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem27, 1, 3, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem28, 2, 0, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem29, 3, 0, 1, 1)
        self.lineEdit_nome_produto = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nome_produto.sizePolicy().hasHeightForWidth())
        self.lineEdit_nome_produto.setSizePolicy(sizePolicy)
        self.lineEdit_nome_produto.setMinimumSize(QtCore.QSize(80, 25))
        self.lineEdit_nome_produto.setMaximumSize(QtCore.QSize(2000, 25))
        self.lineEdit_nome_produto.setMouseTracking(True)
        self.lineEdit_nome_produto.setText("")
        self.lineEdit_nome_produto.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_nome_produto.setObjectName("lineEdit_nome_produto")
        self.gridLayout_4.addWidget(self.lineEdit_nome_produto, 3, 1, 1, 2)
        spacerItem30 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem30, 3, 3, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem31, 4, 0, 1, 1)
        self.lineEdit_quantidade_produto = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_quantidade_produto.sizePolicy().hasHeightForWidth())
        self.lineEdit_quantidade_produto.setSizePolicy(sizePolicy)
        self.lineEdit_quantidade_produto.setMinimumSize(QtCore.QSize(80, 25))
        self.lineEdit_quantidade_produto.setMaximumSize(QtCore.QSize(2000, 25))
        self.lineEdit_quantidade_produto.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_quantidade_produto.setObjectName("lineEdit_quantidade_produto")
        self.gridLayout_4.addWidget(self.lineEdit_quantidade_produto, 4, 1, 1, 2)
        spacerItem32 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem32, 4, 3, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(590, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem33, 5, 0, 1, 2)
        self.btn_salvar_produto = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_salvar_produto.sizePolicy().hasHeightForWidth())
        self.btn_salvar_produto.setSizePolicy(sizePolicy)
        self.btn_salvar_produto.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_salvar_produto.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_salvar_produto.setFont(font)
        self.btn_salvar_produto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salvar_produto.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(205, 241, 252);\n"
"        border-radius:2px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius:15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.btn_salvar_produto.setObjectName("btn_salvar_produto")
        self.gridLayout_4.addWidget(self.btn_salvar_produto, 5, 2, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem34, 5, 3, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(50, 296, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem35, 6, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_7, 0, 1, 1, 1)
        self.tab_pedido.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_10 = QtWidgets.QFrame(self.tab_3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_10.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableWidget_produtos = QtWidgets.QTableWidget(self.frame_10)
        self.tableWidget_produtos.setStyleSheet("QPushButton:hover{\n"
"    border-radius:15px;\n"
"}\n"
"QLineEdit{\n"
"\n"
"    \n"
"    background-color: rgb(255,255,255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QFrame{\n"
"\n"
"    \n"
"        background-color: rgb(227, 230, 230);\n"
"\n"
"}\n"
"")
        self.tableWidget_produtos.setObjectName("tableWidget_produtos")
        self.tableWidget_produtos.setColumnCount(2)
        self.tableWidget_produtos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_produtos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_produtos.setHorizontalHeaderItem(1, item)
        self.gridLayout_10.addWidget(self.tableWidget_produtos, 0, 0, 2, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setStyleSheet("QPushButton{\n"
"    \n"
"        background-color: rgb(227, 230, 230);\n"
"    border-radius:2px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_14.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.btn_alterar_produto = QtWidgets.QPushButton(self.frame_11)
        self.btn_alterar_produto.setMinimumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_alterar_produto.setFont(font)
        self.btn_alterar_produto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_alterar_produto.setStyleSheet("")
        self.btn_alterar_produto.setObjectName("btn_alterar_produto")
        self.verticalLayout_14.addWidget(self.btn_alterar_produto)
        self.btn_deletar_produto = QtWidgets.QPushButton(self.frame_11)
        self.btn_deletar_produto.setMinimumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_deletar_produto.setFont(font)
        self.btn_deletar_produto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_deletar_produto.setObjectName("btn_deletar_produto")
        self.verticalLayout_14.addWidget(self.btn_deletar_produto)
        self.gridLayout_10.addWidget(self.frame_11, 0, 1, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(20, 396, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem36, 1, 1, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem37, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_10, 0, 1, 2, 1)
        spacerItem38 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem38, 0, 2, 2, 1)
        spacerItem39 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem39, 0, 0, 1, 1)
        self.tab_pedido.addTab(self.tab_3, "")
        self.verticalLayout_11.addWidget(self.tab_pedido)
        self.Pages.addWidget(self.pg_cadastro_produto)
        self.pg_cadastro_pedidos = QtWidgets.QWidget()
        self.pg_cadastro_pedidos.setObjectName("pg_cadastro_pedidos")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.pg_cadastro_pedidos)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tab_pedidos = QtWidgets.QTabWidget(self.pg_cadastro_pedidos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_pedidos.sizePolicy().hasHeightForWidth())
        self.tab_pedidos.setSizePolicy(sizePolicy)
        self.tab_pedidos.setObjectName("tab_pedidos")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem40 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem40, 2, 1, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem41, 0, 0, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem42, 0, 2, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.tab_4)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setStyleSheet("QLineEdit{\n"
"\n"
"    \n"
"    background-color: rgb(255,255,255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QFrame{\n"
"\n"
"    \n"
"        background-color: rgb(227, 230, 230);\n"
"\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem43 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem43, 3, 0, 1, 1)
        self.comboBox_clientes = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_clientes.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_clientes.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(100, 100, 100);")
        self.comboBox_clientes.setObjectName("comboBox_clientes")
        self.comboBox_clientes.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_clientes, 3, 1, 1, 2)
        spacerItem44 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem44, 3, 3, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem45, 4, 0, 1, 1)
        self.lineEdit_data_entrega = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_entrega.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_entrega.setSizePolicy(sizePolicy)
        self.lineEdit_data_entrega.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_data_entrega.setMaximumSize(QtCore.QSize(2000, 25))
        self.lineEdit_data_entrega.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_data_entrega.setObjectName("lineEdit_data_entrega")
        self.gridLayout_5.addWidget(self.lineEdit_data_entrega, 4, 1, 1, 2)
        spacerItem46 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem46, 4, 3, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem47, 5, 0, 1, 1)
        self.lineEdit_pedido_descricao = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pedido_descricao.sizePolicy().hasHeightForWidth())
        self.lineEdit_pedido_descricao.setSizePolicy(sizePolicy)
        self.lineEdit_pedido_descricao.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_pedido_descricao.setMaximumSize(QtCore.QSize(2000, 25))
        self.lineEdit_pedido_descricao.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pedido_descricao.setObjectName("lineEdit_pedido_descricao")
        self.gridLayout_5.addWidget(self.lineEdit_pedido_descricao, 5, 1, 1, 2)
        spacerItem48 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem48, 5, 3, 1, 1)
        spacerItem49 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem49, 6, 0, 1, 1)
        self.lineEdit_valor_und = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_valor_und.sizePolicy().hasHeightForWidth())
        self.lineEdit_valor_und.setSizePolicy(sizePolicy)
        self.lineEdit_valor_und.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_valor_und.setMaximumSize(QtCore.QSize(2000, 25))
        self.lineEdit_valor_und.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_valor_und.setObjectName("lineEdit_valor_und")
        self.gridLayout_5.addWidget(self.lineEdit_valor_und, 6, 1, 1, 2)
        spacerItem50 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem50, 6, 3, 1, 1)
        spacerItem51 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem51, 7, 0, 1, 1)
        self.lineEdit_pedidos_quantidade = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pedidos_quantidade.sizePolicy().hasHeightForWidth())
        self.lineEdit_pedidos_quantidade.setSizePolicy(sizePolicy)
        self.lineEdit_pedidos_quantidade.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_pedidos_quantidade.setMaximumSize(QtCore.QSize(2000, 25))
        self.lineEdit_pedidos_quantidade.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pedidos_quantidade.setObjectName("lineEdit_pedidos_quantidade")
        self.gridLayout_5.addWidget(self.lineEdit_pedidos_quantidade, 7, 1, 1, 2)
        spacerItem52 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem52, 7, 3, 1, 1)
        spacerItem53 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem53, 8, 0, 1, 1)
        spacerItem54 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem54, 8, 3, 1, 1)
        spacerItem55 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem55, 9, 0, 1, 2)
        self.btn_salvar_pedido = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_salvar_pedido.sizePolicy().hasHeightForWidth())
        self.btn_salvar_pedido.setSizePolicy(sizePolicy)
        self.btn_salvar_pedido.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_salvar_pedido.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_salvar_pedido.setFont(font)
        self.btn_salvar_pedido.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salvar_pedido.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(205, 241, 252);\n"
"        border-radius:2px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius:15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.btn_salvar_pedido.setObjectName("btn_salvar_pedido")
        self.gridLayout_5.addWidget(self.btn_salvar_pedido, 9, 2, 1, 1)
        spacerItem56 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem56, 9, 3, 1, 1)
        spacerItem57 = QtWidgets.QSpacerItem(20, 106, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem57, 10, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 4)
        spacerItem58 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem58, 2, 0, 1, 4)
        spacerItem59 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem59, 0, 0, 1, 4)
        self.lineEdit_valor_total = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_valor_total.sizePolicy().hasHeightForWidth())
        self.lineEdit_valor_total.setSizePolicy(sizePolicy)
        self.lineEdit_valor_total.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_valor_total.setMaximumSize(QtCore.QSize(2000, 25))
        self.lineEdit_valor_total.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_valor_total.setObjectName("lineEdit_valor_total")
        self.gridLayout_5.addWidget(self.lineEdit_valor_total, 8, 1, 1, 2)
        self.gridLayout_6.addWidget(self.frame_6, 0, 1, 2, 1)
        self.tab_pedidos.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem60 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem60, 1, 2, 1, 1)
        spacerItem61 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem61, 1, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.tab_5)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_12.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_12.setHorizontalSpacing(0)
        self.gridLayout_12.setVerticalSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem62 = QtWidgets.QSpacerItem(20, 366, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem62, 1, 1, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame_13.setFont(font)
        self.frame_13.setStyleSheet("QPushButton{\n"
"    \n"
"        background-color: rgb(227, 230, 230);\n"
"    border-radius:2px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_15.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.btn_alterar_pedido = QtWidgets.QPushButton(self.frame_13)
        self.btn_alterar_pedido.setMinimumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_alterar_pedido.setFont(font)
        self.btn_alterar_pedido.setObjectName("btn_alterar_pedido")
        self.verticalLayout_15.addWidget(self.btn_alterar_pedido)
        self.btn_deletar_pedido = QtWidgets.QPushButton(self.frame_13)
        self.btn_deletar_pedido.setMinimumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_deletar_pedido.setFont(font)
        self.btn_deletar_pedido.setObjectName("btn_deletar_pedido")
        self.verticalLayout_15.addWidget(self.btn_deletar_pedido)
        self.gridLayout_12.addWidget(self.frame_13, 0, 1, 1, 1)
        self.tableWidget_pedidos = QtWidgets.QTableWidget(self.frame_12)
        self.tableWidget_pedidos.setStyleSheet("QLineEdit{\n"
"\n"
"    \n"
"    background-color: rgb(255,255,255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QFrame{\n"
"\n"
"    \n"
"        background-color: rgb(227, 230, 230);\n"
"\n"
"}\n"
"")
        self.tableWidget_pedidos.setObjectName("tableWidget_pedidos")
        self.tableWidget_pedidos.setColumnCount(6)
        self.tableWidget_pedidos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pedidos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pedidos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pedidos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pedidos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pedidos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pedidos.setHorizontalHeaderItem(5, item)
        self.gridLayout_12.addWidget(self.tableWidget_pedidos, 0, 0, 2, 1)
        spacerItem63 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem63, 2, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_12, 0, 1, 2, 1)
        self.tab_pedidos.addTab(self.tab_5, "")
        self.verticalLayout_12.addWidget(self.tab_pedidos)
        self.Pages.addWidget(self.pg_cadastro_pedidos)
        self.pg_historico = QtWidgets.QWidget()
        self.pg_historico.setObjectName("pg_historico")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.pg_historico)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem64 = QtWidgets.QSpacerItem(1, 528, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem64, 0, 0, 4, 2)
        self.label = QtWidgets.QLabel(self.pg_historico)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.gridLayout_14.addWidget(self.label, 0, 2, 1, 2)
        spacerItem65 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem65, 0, 4, 1, 1)
        spacerItem66 = QtWidgets.QSpacerItem(1, 508, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem66, 0, 5, 3, 1)
        self.tableWidget_historico = QtWidgets.QTableWidget(self.pg_historico)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_historico.sizePolicy().hasHeightForWidth())
        self.tableWidget_historico.setSizePolicy(sizePolicy)
        self.tableWidget_historico.setStyleSheet("QLineEdit{\n"
"\n"
"    \n"
"    background-color: rgb(255,255,255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QFrame{\n"
"\n"
"    \n"
"        background-color: rgb(227, 230, 230);\n"
"\n"
"}")
        self.tableWidget_historico.setObjectName("tableWidget_historico")
        self.tableWidget_historico.setColumnCount(6)
        self.tableWidget_historico.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historico.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historico.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historico.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historico.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historico.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historico.setHorizontalHeaderItem(5, item)
        self.gridLayout_14.addWidget(self.tableWidget_historico, 1, 2, 2, 1)
        self.frame_4 = QtWidgets.QFrame(self.pg_historico)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(100, 100))
        self.frame_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_4.setStyleSheet("QPushButton{\n"
"    \n"
"        background-color: rgb(227, 230, 230);\n"
"    border-radius:2px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout.setContentsMargins(-1, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(9)
        self.formLayout.setObjectName("formLayout")
        self.btn_pdf = QtWidgets.QPushButton(self.frame_4)
        self.btn_pdf.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_pdf.setObjectName("btn_pdf")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.btn_pdf)
        self.btn_excel = QtWidgets.QPushButton(self.frame_4)
        self.btn_excel.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_excel.setObjectName("btn_excel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.btn_excel)
        spacerItem67 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem67)
        self.gridLayout_14.addWidget(self.frame_4, 1, 3, 1, 2)
        spacerItem68 = QtWidgets.QSpacerItem(666, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_14.addItem(spacerItem68, 3, 1, 1, 5)
        spacerItem69 = QtWidgets.QSpacerItem(1, 379, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_14.addItem(spacerItem69, 2, 3, 1, 1)
        self.Pages.addWidget(self.pg_historico)
        self.verticalLayout_6.addWidget(self.Pages)
        self.verticalLayout.addWidget(self.main_frame)
        self.footer_frame = QtWidgets.QFrame(self.main_container)
        self.footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer_frame)
        self.horizontalLayout_3.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.footer_frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.footer_frame)
        self.gridLayout_13.addWidget(self.main_container, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.Pages.setCurrentIndex(0)
        self.tab_cliente.setCurrentIndex(1)
        self.tab_pedido.setCurrentIndex(1)
        self.tab_pedidos.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_home.setText(_translate("MainWindow", "Gestec"))
        self.btn_cliente.setText(_translate("MainWindow", "Clientes"))
        self.btn_produtos.setText(_translate("MainWindow", "Produtos"))
        self.btn_pedidos.setText(_translate("MainWindow", "Pedidos"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_cadastro), _translate("MainWindow", "Cadastro"))
        self.btn_gerar_relatorio.setText(_translate("MainWindow", "Gerar Relatório"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_historico), _translate("MainWindow", "Histórico"))
        self.top_frame.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bfecf8;\">Sistema de Cadastro e Faturamento</span></p></body></html>"))
        self.logo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\"file:///C:/Users/thayl/OneDrive/Área de Trabalho/Projeto 4 Semestre/img/logo4.png\"/></p></body></html>"))
        self.lineEdit_nome_cliente.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.btn_salvar_cliente.setText(_translate("MainWindow", "Salvar"))
        self.lineEdit_contato_cliente.setPlaceholderText(_translate("MainWindow", "Contato"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#004a70;\">Cliente</span></p></body></html>"))
        self.tab_cliente.setTabText(self.tab_cliente.indexOf(self.tab_1), _translate("MainWindow", "Cadastro"))
        item = self.tableWidget_cliente.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cliente"))
        item = self.tableWidget_cliente.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Contato"))
        self.btn_alterar_cliente.setText(_translate("MainWindow", "Alterar"))
        self.btn_deletar_cliente.setText(_translate("MainWindow", "Deletar"))
        self.tab_cliente.setTabText(self.tab_cliente.indexOf(self.tab_2), _translate("MainWindow", "Lista"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#004a70;\">Produtos</span></p></body></html>"))
        self.lineEdit_nome_produto.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.lineEdit_quantidade_produto.setPlaceholderText(_translate("MainWindow", "Quantidade"))
        self.btn_salvar_produto.setText(_translate("MainWindow", "Salvar"))
        self.tab_pedido.setTabText(self.tab_pedido.indexOf(self.tab), _translate("MainWindow", "Cadastro"))
        item = self.tableWidget_produtos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tableWidget_produtos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantidade"))
        self.btn_alterar_produto.setText(_translate("MainWindow", "Alterar"))
        self.btn_deletar_produto.setText(_translate("MainWindow", "Deletar"))
        self.tab_pedido.setTabText(self.tab_pedido.indexOf(self.tab_3), _translate("MainWindow", "Lista"))
        self.comboBox_clientes.setItemText(0, _translate("MainWindow", "Cliente"))
        self.lineEdit_data_entrega.setPlaceholderText(_translate("MainWindow", "Data de Entrega"))
        self.lineEdit_pedido_descricao.setPlaceholderText(_translate("MainWindow", "Descrição"))
        self.lineEdit_valor_und.setPlaceholderText(_translate("MainWindow", "Valor Und"))
        self.lineEdit_pedidos_quantidade.setPlaceholderText(_translate("MainWindow", "Quantidade"))
        self.btn_salvar_pedido.setText(_translate("MainWindow", "Salvar"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#004a70;\">Pedidos</span></p></body></html>"))
        self.lineEdit_valor_total.setPlaceholderText(_translate("MainWindow", "Valor Total"))
        self.tab_pedidos.setTabText(self.tab_pedidos.indexOf(self.tab_4), _translate("MainWindow", "Cadastro"))
        self.btn_alterar_pedido.setText(_translate("MainWindow", "Alterar"))
        self.btn_deletar_pedido.setText(_translate("MainWindow", "Deletar"))
        item = self.tableWidget_pedidos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cliente"))
        item = self.tableWidget_pedidos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Descrição"))
        item = self.tableWidget_pedidos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Valor Und"))
        item = self.tableWidget_pedidos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quantidade"))
        item = self.tableWidget_pedidos.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Valor Total"))
        item = self.tableWidget_pedidos.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Data de Entrega"))
        self.tab_pedidos.setTabText(self.tab_pedidos.indexOf(self.tab_5), _translate("MainWindow", "Lista"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Relatório</span></p></body></html>"))
        item = self.tableWidget_historico.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Data de Entrega"))
        item = self.tableWidget_historico.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cliente"))
        item = self.tableWidget_historico.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Descrição"))
        item = self.tableWidget_historico.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Valor_und"))
        item = self.tableWidget_historico.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Quantidade"))
        item = self.tableWidget_historico.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Valor_Total"))
        self.btn_pdf.setText(_translate("MainWindow", "Gerar PDF"))
        self.btn_excel.setText(_translate("MainWindow", "Gerar EXCEL"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">º GESTEC 2024</span></p></body></html>"))
